TEMPLATE = lib
CONFIG += qt warn_on c++17 staticlib
QT += core network xml
TARGET = xenlib
DEFINES += XENLIB_LIBRARY

# Windows: building/using static library; disable dllimport/export in headers
win32:DEFINES += XENLIB_STATIC

# Source files
SOURCES += \
    xen/actions/vm/vmstartaction.cpp \
    xenlib.cpp \
    xencache.cpp \
    vmhelpers.cpp \
    metricupdater.cpp \
    groupingtag.cpp \
    grouping.cpp \
    queryscope.cpp \
    queryfilter.cpp \
    query.cpp \
    search.cpp \
    xen/connection.cpp \
    xen/connectionworker.cpp \
    xen/session.cpp \
    xen/api.cpp \
    xen/apiversion.cpp \
    xen/jsonrpcclient.cpp \
    xen/asyncoperations.cpp \
    xen/eventpoller.cpp \
    xen/certificatemanager.cpp \
    xen/heartbeat.cpp \
    xen/asyncoperation.cpp \
    xen/xenobject.cpp \
    xen/pool.cpp \
    xen/host.cpp \
    xen/vm.cpp \
    xen/sr.cpp \
    xen/vdi.cpp \
    xen/vbd.cpp \
    xen/xenapi/xenapi_VM.cpp \
    xen/xenapi/VDI.cpp \
    xen/xenapi/VBD.cpp \
    xen/xenapi/xenapi_SR.cpp \
    xen/xenapi/PBD.cpp \
    xen/xenapi/xenapi_Pool.cpp \
    xen/xenapi/Secret.cpp \
    xen/xenapi/xenapi_Host.cpp \
    xen/xenapi/Network.cpp \
    xen/xenapi/Bond.cpp \
    xen/xenapi/PIF.cpp \
    xen/xenapi/Network_sriov.cpp \
    xen/xenapi/VIF.cpp \
    xen/xenapi/VGPU.cpp \
    xen/xenapi/vm_appliance.cpp \
    xen/actions/vm/changevmisoaction.cpp \
    xen/actions/vm/startapplianceaction.cpp \
    xen/actions/vm/shutdownapplianceaction.cpp \
    xen/actions/vm/hvmbootaction.cpp \
    xen/actions/sr/srcreateaction.cpp \
    xen/actions/sr/srintroduceaction.cpp \
    xen/actions/sr/srreattachaction.cpp \
    xen/actions/sr/srrepairaction.cpp \
    xen/actions/sr/srtrimaction.cpp \
    xen/actions/sr/srprobeaction.cpp \
    xen/actions/sr/srscanaction.cpp \
    xen/actions/sr/srrefreshaction.cpp \
    xen/actions/sr/detachsraction.cpp \
    xen/actions/sr/forgetsraction.cpp \
    xen/actions/sr/destroysraction.cpp \
    xen/actions/host/reboothostaction.cpp \
    xen/actions/host/shutdownhostaction.cpp \
    xen/actions/host/enablehostaction.cpp \
    xen/actions/host/disablehostaction.cpp \
    xen/actions/host/evacuatehostaction.cpp \
    xen/actions/host/destroyhostaction.cpp \
    xen/actions/host/changehostautostartaction.cpp \
    xen/actions/host/editmultipathaction.cpp \
    xen/actions/host/savepoweronsettingsaction.cpp \
    xen/actions/vdi/creatediskaction.cpp \
    xen/actions/vdi/detachvirtualdiskaction.cpp \
    xen/actions/vdi/destroydiskaction.cpp \
    xen/actions/vdi/movevirtualdiskaction.cpp \
    xen/actions/vdi/migratevirtualdiskaction.cpp \
    xen/actions/vdi/vdidisablecbtaction.cpp \
    xen/actions/vbd/vbdcreateandplugaction.cpp \
    xen/actions/general/generaleditpageaction.cpp \
    xen/actions/vm/vmstartabstractaction.cpp \
    xen/actions/vm/vmstartonaction.cpp \
    xen/actions/vm/vmresumeaction.cpp \
    xen/actions/vm/vmresumeonaction.cpp \
    xen/actions/vm/vmshutdownaction.cpp \
    xen/actions/vm/vmrebootaction.cpp \
    xen/actions/vm/vmpauseaction.cpp \
    xen/actions/vm/vmdestroyaction.cpp \
    xen/actions/vm/vmcloneaction.cpp \
    xen/actions/vm/vmtotemplateaction.cpp \
    xen/actions/vm/createvmfastaction.cpp \
    xen/actions/vm/vmsnapshotcreateaction.cpp \
    xen/actions/vm/vmsnapshotdeleteaction.cpp \
    xen/actions/vm/vmsnapshotrevertaction.cpp \
    xen/actions/vm/changememorysettingsaction.cpp \
    xen/actions/vm/changevcpusettingsaction.cpp \
    xen/actions/vm/gpuassignaction.cpp \
    xen/actions/vm/vmmigrateaction.cpp \
    xen/actions/vm/vmcrosspoolmigrateaction.cpp \
    xen/actions/vm/vmcopyaction.cpp \
    xen/actions/pool/addhosttopoolaction.cpp \
    xen/actions/pool/createpoolaction.cpp \
    xen/actions/pool/ejecthostfrompoolaction.cpp \
    xen/actions/pool/destroypoolaction.cpp \
    xen/actions/pool/rotatepoolsecretaction.cpp \
    xen/actions/pool/enablehaaction.cpp \
    xen/actions/pool/disablehaaction.cpp \
    xen/actions/pool/sethaprioritiesaction.cpp \
    xen/actions/pool/emergencytransitiontomasteraction.cpp \
    xen/actions/pool/designatenewmasteraction.cpp \
    xen/actions/pool/syncdatabaseaction.cpp \
    xen/actions/pool/setpoolnameanddescriptionaction.cpp \
    xen/actions/network/changenetworkingaction.cpp \
    xen/actions/network/createbondaction.cpp \
    xen/actions/network/destroybondaction.cpp \
    xen/actions/network/createsriovaction.cpp \
    xen/actions/network/networkingactionhelpers.cpp \
    xen/actions/network/rescanpifsaction.cpp \
    xen/actions/vif/createvifaction.cpp \
    xen/actions/vif/deletevifaction.cpp \
    xen/actions/vif/plugvifaction.cpp \
    xen/actions/vif/unplugvifaction.cpp \
    xen/actions/vif/updatevifaction.cpp \
    xen/actions/delegatedasyncoperation.cpp \
    utils/encryption.cpp \
    collections/connectionsmanager.cpp \
    operations/producerconsumerqueue.cpp \
    operations/multipleoperation.cpp \
    operations/paralleloperation.cpp \
    operations/operationlauncher.cpp

# Header files
HEADERS += \
    xen/actions/vm/vmstartaction.h \
    xenlib.h \
    xenlib_global.h \
    xencache.h \
    vmhelpers.h \
    metricupdater.h \
    groupingtag.h \
    grouping.h \
    queryscope.h \
    queryfilter.h \
    query.h \
    search.h \
    xen/connection.h \
    xen/connectionworker.h \
    xen/session.h \
    xen/api.h \
    xen/apiversion.h \
    xen/jsonrpcclient.h \
    xen/asyncoperations.h \
    xen/eventpoller.h \
    xen/certificatemanager.h \
    xen/heartbeat.h \
    xen/asyncoperation.h \
    xen/xenobject.h \
    xen/pool.h \
    xen/host.h \
    xen/vm.h \
    xen/sr.h \
    xen/vdi.h \
    xen/vbd.h \
    xen/xenapi/xenapi_VM.h \
    xen/xenapi/VDI.h \
    xen/xenapi/VBD.h \
    xen/xenapi/xenapi_SR.h \
    xen/xenapi/PBD.h \
    xen/xenapi/xenapi_Pool.h \
    xen/xenapi/Secret.h \
    xen/xenapi/xenapi_Host.h \
    xen/xenapi/Network.h \
    xen/xenapi/Bond.h \
    xen/xenapi/PIF.h \
    xen/xenapi/Network_sriov.h \
    xen/xenapi/VIF.h \
    xen/xenapi/VGPU.h \
    xen/xenapi/vm_appliance.h \
    xen/actions/vm/changevmisoaction.h \
    xen/actions/vm/startapplianceaction.h \
    xen/actions/vm/shutdownapplianceaction.h \
    xen/actions/vm/hvmbootaction.h \
    xen/actions/sr/srcreateaction.h \
    xen/actions/sr/srintroduceaction.h \
    xen/actions/sr/srreattachaction.h \
    xen/actions/sr/srrepairaction.h \
    xen/actions/sr/srtrimaction.h \
    xen/actions/sr/srrefreshaction.h \
    xen/actions/sr/detachsraction.h \
    xen/actions/sr/forgetsraction.h \
    xen/actions/sr/destroysraction.h \
    xen/actions/host/destroyhostaction.h \
    xen/actions/host/changehostautostartaction.h \
    xen/actions/host/editmultipathaction.h \
    xen/actions/host/savepoweronsettingsaction.h \
    xen/actions/vdi/creatediskaction.h \
    xen/actions/vdi/detachvirtualdiskaction.h \
    xen/actions/vdi/destroydiskaction.h \
    xen/actions/vdi/movevirtualdiskaction.h \
    xen/actions/vdi/migratevirtualdiskaction.h \
    xen/actions/vdi/vdidisablecbtaction.h \
    xen/actions/vbd/vbdcreateandplugaction.h \
    xen/actions/general/generaleditpageaction.h \
    xen/actions/vm/vmstartabstractaction.h \
    xen/actions/vm/vmstartonaction.h \
    xen/actions/vm/vmresumeaction.h \
    xen/actions/vm/vmresumeonaction.h \
    xen/actions/vm/vmshutdownaction.h \
    xen/actions/vm/vmrebootaction.h \
    xen/actions/vm/vmpauseaction.h \
    xen/actions/vm/vmdestroyaction.h \
    xen/actions/vm/vmcloneaction.h \
    xen/actions/vm/vmtotemplateaction.h \
    xen/actions/vm/createvmfastaction.h \
    xen/actions/vm/vmsnapshotcreateaction.h \
    xen/actions/vm/vmsnapshotdeleteaction.h \
    xen/actions/vm/vmsnapshotrevertaction.h \
    xen/actions/vm/changememorysettingsaction.h \
    xen/actions/vm/changevcpusettingsaction.h \
    xen/actions/vm/gpuassignaction.h \
    xen/actions/vm/vmmigrateaction.h \
    xen/actions/vm/vmcrosspoolmigrateaction.h \
    xen/actions/vm/vmcopyaction.h \
    xen/actions/pool/addhosttopoolaction.h \
    xen/actions/pool/createpoolaction.h \
    xen/actions/pool/ejecthostfrompoolaction.h \
    xen/actions/pool/destroypoolaction.h \
    xen/actions/pool/rotatepoolsecretaction.h \
    xen/actions/pool/enablehaaction.h \
    xen/actions/pool/disablehaaction.h \
    xen/actions/pool/sethaprioritiesaction.h \
    xen/actions/pool/emergencytransitiontomasteraction.h \
    xen/actions/pool/designatenewmasteraction.h \
    xen/actions/pool/syncdatabaseaction.h \
    xen/actions/pool/setpoolnameanddescriptionaction.h \
    xen/actions/network/changenetworkingaction.h \
    xen/actions/network/createbondaction.h \
    xen/actions/network/destroybondaction.h \
    xen/actions/network/createsriovaction.h \
    xen/actions/network/networkingactionhelpers.h \
    xen/actions/network/rescanpifsaction.h \
    xen/actions/vif/createvifaction.h \
    xen/actions/vif/deletevifaction.h \
    xen/actions/vif/plugvifaction.h \
    xen/actions/vif/unplugvifaction.h \
    xen/actions/vif/updatevifaction.h \
    xen/actions/delegatedasyncoperation.h \
    utils/encryption.h \
    collections/observablelist.h \
    collections/connectionsmanager.h \
    operations/producerconsumerqueue.h \
    operations/multipleoperation.h \
    operations/paralleloperation.h \
    operations/operationlauncher.h

# Installation
target.path = $$[QT_INSTALL_LIBS]
INSTALLS += target
