TEMPLATE = lib
CONFIG += qt warn_on c++17 staticlib
QT += core network xml
TARGET = xenlib
DEFINES += XENLIB_LIBRARY

greaterThan(QT_MAJOR_VERSION, 5) {
    DEFINES += QT_NO_DEPRECATED_WARNINGS
}

# Windows: building/using static library; disable dllimport/export in headers
win32:DEFINES += XENLIB_STATIC

# Source files
SOURCES += \
    utils/misc.cpp \
    xen/actions/vm/vmstartaction.cpp \
    xen/xenapi/xenapi_Blob.cpp \
    xen/xenapi/xenapi_Bond.cpp \
    xen/xenapi/xenapi_Network.cpp \
    xen/xenapi/xenapi_Network_sriov.cpp \
    xen/xenapi/xenapi_PBD.cpp \
    xen/xenapi/xenapi_PIF.cpp \
    xen/xenapi/xenapi_Secret.cpp \
    xen/xenapi/xenapi_VBD.cpp \
    xen/xenapi/xenapi_VDI.cpp \
    xen/xenapi/xenapi_VGPU.cpp \
    xen/xenapi/xenapi_VIF.cpp \
    xencache.cpp \
    vmhelpers.cpp \
    metricupdater.cpp \
    xensearch/common.cpp \
    xensearch/group.cpp \
    xensearch/groupingtag.cpp \
    xensearch/grouping.cpp \
    xensearch/queryscope.cpp \
    xensearch/queryfilter.cpp \
    xensearch/queries.cpp \
    xensearch/propertyaccessorhelper.cpp \
    xensearch/query.cpp \
    xensearch/search.cpp \
    xensearch/sort.cpp \
    xen/network/connection.cpp \
    xen/network/connectionworker.cpp \
    xen/network/httpclient.cpp \
    xen/session.cpp \
    xen/api.cpp \
    xen/apiversion.cpp \
    xen/jsonrpcclient.cpp \
    xen/eventpoller.cpp \
    xen/network/certificatemanager.cpp \
    xen/network/heartbeat.cpp \
    xen/failure.cpp \
    xen/friendlyerrornames.cpp \
    xen/asyncoperation.cpp \
    xen/xenobject.cpp \
    xen/vmappliance.cpp \
    xen/pool.cpp \
    xen/host.cpp \
    xen/hostmetrics.cpp \
    xen/vm.cpp \
    xen/sr.cpp \
    xen/vdi.cpp \
    xen/vbd.cpp \
    xen/pbd.cpp \
    xen/pif.cpp \
    xen/vusb.cpp \
    xen/vtpm.cpp \
    xen/vmss.cpp \
    xen/vmpp.cpp \
    xen/vgpu.cpp \
    xen/pci.cpp \
    xen/pgpu.cpp \
    xen/network.cpp \
    xen/task.cpp \
    xen/xenapi/xenapi_VM.cpp \
    xen/xenapi/xenapi_SR.cpp \
    xen/xenapi/xenapi_Pool.cpp \
    xen/xenapi/xenapi_Host.cpp \
    xen/xenapi/xenapi_Task.cpp \
    xen/xenapi/xenapi_Session.cpp \
    xen/xenapi/xenapi_Role.cpp \
    xen/xenapi/xenapi_UserDetails.cpp \
    xen/xenapi/xenapi_Helper.cpp \
    xen/xenapi/vm_appliance.cpp \
    xen/actions/vm/changevmisoaction.cpp \
    xen/actions/vm/importvmaction.cpp \
    xen/actions/vm/exportvmaction.cpp \
    xen/actions/vm/startapplianceaction.cpp \
    xen/actions/vm/shutdownapplianceaction.cpp \
    xen/actions/vm/hvmbootaction.cpp \
    xen/actions/sr/srcreateaction.cpp \
    xen/actions/sr/srintroduceaction.cpp \
    xen/actions/sr/srreattachaction.cpp \
    xen/actions/sr/srrepairaction.cpp \
    xen/actions/sr/srtrimaction.cpp \
    xen/actions/sr/srprobeaction.cpp \
    xen/actions/sr/srscanaction.cpp \
    xen/actions/sr/srrefreshaction.cpp \
    xen/actions/sr/detachsraction.cpp \
    xen/actions/sr/forgetsraction.cpp \
    xen/actions/sr/destroysraction.cpp \
    xen/actions/host/reboothostaction.cpp \
    xen/actions/host/shutdownhostaction.cpp \
    xen/actions/host/restarttoolstackaction.cpp \
    xen/actions/host/enablehostaction.cpp \
    xen/actions/host/disablehostaction.cpp \
    xen/actions/host/evacuatehostaction.cpp \
    xen/actions/host/destroyhostaction.cpp \
    xen/actions/host/changehostautostartaction.cpp \
    xen/actions/host/editmultipathaction.cpp \
    xen/actions/host/savepoweronsettingsaction.cpp \
    xen/actions/vdi/creatediskaction.cpp \
    xen/actions/vdi/detachvirtualdiskaction.cpp \
    xen/actions/vdi/destroydiskaction.cpp \
    xen/actions/vdi/movevirtualdiskaction.cpp \
    xen/actions/vdi/migratevirtualdiskaction.cpp \
    xen/actions/vdi/vdidisablecbtaction.cpp \
    xen/actions/vbd/vbdcreateandplugaction.cpp \
    xen/actions/general/generaleditpageaction.cpp \
    xen/actions/vm/vmstartabstractaction.cpp \
    xen/actions/vm/vmstartonaction.cpp \
    xen/actions/vm/vmresumeaction.cpp \
    xen/actions/vm/vmresumeonaction.cpp \
    xen/actions/vm/vmshutdownaction.cpp \
    xen/actions/vm/vmrebootaction.cpp \
    xen/actions/vm/vmpauseaction.cpp \
    xen/actions/vm/vmdestroyaction.cpp \
    xen/actions/vm/vmcloneaction.cpp \
    xen/actions/vm/vmtotemplateaction.cpp \
    xen/actions/vm/createvmfastaction.cpp \
    xen/actions/vm/createvmaction.cpp \
    xen/actions/vm/vmsnapshotcreateaction.cpp \
    xen/actions/vm/vmsnapshotdeleteaction.cpp \
    xen/actions/vm/vmsnapshotrevertaction.cpp \
    xen/actions/vm/changememorysettingsaction.cpp \
    xen/actions/vm/changevcpusettingsaction.cpp \
    xen/actions/vm/setvmstartupoptionsaction.cpp \
    xen/actions/vm/gpuassignaction.cpp \
    xen/actions/vm/vmmigrateaction.cpp \
    xen/actions/vm/vmcrosspoolmigrateaction.cpp \
    xen/actions/vm/vmcopyaction.cpp \
    xen/actions/vm/vmmoveaction.cpp \
    xen/actions/pool/addhosttopoolaction.cpp \
    xen/actions/pool/createpoolaction.cpp \
    xen/actions/pool/ejecthostfrompoolaction.cpp \
    xen/actions/pool/destroypoolaction.cpp \
    xen/actions/pool/rotatepoolsecretaction.cpp \
    xen/actions/pool/enablehaaction.cpp \
    xen/actions/pool/disablehaaction.cpp \
    xen/actions/pool/sethaprioritiesaction.cpp \
    xen/actions/pool/emergencytransitiontomasteraction.cpp \
    xen/actions/pool/designatenewmasteraction.cpp \
    xen/actions/pool/syncdatabaseaction.cpp \
    xen/actions/pool/setpoolnameanddescriptionaction.cpp \
    xen/actions/pool/setsrasdefaultaction.cpp \
    xen/actions/pool/setpoolpropertyaction.cpp \
    xen/actions/pool/setssllegacyaction.cpp \
    xen/actions/network/changenetworkingaction.cpp \
    xen/actions/network/createbondaction.cpp \
    xen/actions/network/destroybondaction.cpp \
    xen/actions/network/createsriovaction.cpp \
    xen/actions/network/networkingactionhelpers.cpp \
    xen/actions/network/rescanpifsaction.cpp \
    xen/actions/vif/createvifaction.cpp \
    xen/actions/vif/deletevifaction.cpp \
    xen/actions/vif/plugvifaction.cpp \
    xen/actions/vif/unplugvifaction.cpp \
    xen/actions/vif/updatevifaction.cpp \
    xen/actions/delegatedasyncoperation.cpp \
    utils/encryption.cpp \
    network/comparableaddress.cpp \
    xen/network/connectionsmanager.cpp \
    operations/producerconsumerqueue.cpp \
    operations/multipleoperation.cpp \
    operations/paralleloperation.cpp \
    operations/operationlauncher.cpp \
    customfields/customfielddefinition.cpp \
    customfields/customfieldsmanager.cpp \
    xen/dockercontainer.cpp \
    xen/folder.cpp \
    xen/blob.cpp \
    xen/bond.cpp \
    xen/certificate.cpp \
    xen/cluster.cpp \
    xen/console.cpp \
    xen/event.cpp \
    xen/feature.cpp \
    xen/gpugroup.cpp \
    xen/hostcpu.cpp \
    xen/hostcrashdump.cpp \
    xen/hostpatch.cpp \
    xen/poolpatch.cpp \
    xen/poolupdate.cpp \
    xen/pusb.cpp \
    xen/sm.cpp \
    xen/role.cpp \
    xen/user.cpp \
    otherconfig/otherconfigandtagswatcher.cpp

# Header files
HEADERS += \
    utils/misc.h \
    xen/actions/vm/vmstartaction.h \
    xen/xenapi/xenapi_Blob.h \
    xen/xenapi/xenapi_Bond.h \
    xen/xenapi/xenapi_Network.h \
    xen/xenapi/xenapi_Network_sriov.h \
    xen/xenapi/xenapi_PBD.h \
    xen/xenapi/xenapi_PIF.h \
    xen/xenapi/xenapi_Secret.h \
    xen/xenapi/xenapi_VBD.h \
    xen/xenapi/xenapi_VDI.h \
    xen/xenapi/xenapi_VGPU.h \
    xen/xenapi/xenapi_VIF.h \
    xenlib_global.h \
    xencache.h \
    vmhelpers.h \
    metricupdater.h \
    xensearch/common.h \
    xensearch/group.h \
    xensearch/groupingtag.h \
    xensearch/grouping.h \
    xensearch/queryscope.h \
    xensearch/queryfilter.h \
    xensearch/queries.h \
    xensearch/propertyaccessorhelper.h \
    xensearch/query.h \
    xensearch/search.h \
    xensearch/sort.h \
    xensearch/iacceptgroups.h \
    xen/network/connection.h \
    xen/network/connectionworker.h \
    xen/network/httpclient.h \
    xen/network/connecttask.h \
    xen/session.h \
    xen/api.h \
    xen/apiversion.h \
    xen/jsonrpcclient.h \
    xen/eventpoller.h \
    xen/network/certificatemanager.h \
    xen/network/heartbeat.h \
    xen/failure.h \
    xen/friendlyerrornames.h \
    xen/asyncoperation.h \
    xen/xenobject.h \
    xen/pool.h \
    xen/host.h \
    xen/hostmetrics.h \
    xen/vm.h \
    xen/mappings/vmmapping.h \
    xen/sr.h \
    xen/vdi.h \
    xen/vbd.h \
    xen/pbd.h \
    xen/pif.h \
    xen/vusb.h \
    xen/vtpm.h \
    xen/vmss.h \
    xen/vmpp.h \
    xen/vgpu.h \
    xen/pci.h \
    xen/pgpu.h \
    xen/network.h \
    xen/task.h \
    xen/vmappliance.h \
    xen/xenapi/xenapi_VM.h \
    xen/xenapi/xenapi_SR.h \
    xen/xenapi/xenapi_Pool.h \
    xen/xenapi/xenapi_Host.h \
    xen/xenapi/xenapi_Task.h \
    xen/xenapi/xenapi_Session.h \
    xen/xenapi/xenapi_Role.h \
    xen/xenapi/xenapi_UserDetails.h \
    xen/xenapi/xenapi_Helper.h \
    xen/xenapi/vm_appliance.h \
    xen/actions/vm/changevmisoaction.h \
    xen/actions/vm/importvmaction.h \
    xen/actions/vm/exportvmaction.h \
    xen/actions/vm/startapplianceaction.h \
    xen/actions/vm/shutdownapplianceaction.h \
    xen/actions/vm/hvmbootaction.h \
    xen/actions/sr/srcreateaction.h \
    xen/actions/sr/srintroduceaction.h \
    xen/actions/sr/srreattachaction.h \
    xen/actions/sr/srrepairaction.h \
    xen/actions/sr/srtrimaction.h \
    xen/actions/sr/srrefreshaction.h \
    xen/actions/sr/detachsraction.h \
    xen/actions/sr/forgetsraction.h \
    xen/actions/sr/destroysraction.h \
    xen/actions/host/reboothostaction.h \
    xen/actions/host/shutdownhostaction.h \
    xen/actions/host/restarttoolstackaction.h \
    xen/actions/host/enablehostaction.h \
    xen/actions/host/disablehostaction.h \
    xen/actions/host/evacuatehostaction.h \
    xen/actions/host/destroyhostaction.h \
    xen/actions/host/changehostautostartaction.h \
    xen/actions/host/editmultipathaction.h \
    xen/actions/host/savepoweronsettingsaction.h \
    xen/actions/vdi/creatediskaction.h \
    xen/actions/vdi/detachvirtualdiskaction.h \
    xen/actions/vdi/destroydiskaction.h \
    xen/actions/vdi/movevirtualdiskaction.h \
    xen/actions/vdi/migratevirtualdiskaction.h \
    xen/actions/vdi/vdidisablecbtaction.h \
    xen/actions/vbd/vbdcreateandplugaction.h \
    xen/actions/general/generaleditpageaction.h \
    xen/actions/vm/vmstartabstractaction.h \
    xen/actions/vm/vmstartonaction.h \
    xen/actions/vm/vmresumeaction.h \
    xen/actions/vm/vmresumeonaction.h \
    xen/actions/vm/vmshutdownaction.h \
    xen/actions/vm/vmrebootaction.h \
    xen/actions/vm/vmpauseaction.h \
    xen/actions/vm/vmdestroyaction.h \
    xen/actions/vm/vmcloneaction.h \
    xen/actions/vm/vmtotemplateaction.h \
    xen/actions/vm/createvmfastaction.h \
    xen/actions/vm/createvmaction.h \
    xen/actions/vm/vmsnapshotcreateaction.h \
    xen/actions/vm/vmsnapshotdeleteaction.h \
    xen/actions/vm/vmsnapshotrevertaction.h \
    xen/actions/vm/changememorysettingsaction.h \
    xen/actions/vm/changevcpusettingsaction.h \
    xen/actions/vm/setvmstartupoptionsaction.h \
    xen/actions/vm/gpuassignaction.h \
    xen/actions/vm/vmmigrateaction.h \
    xen/actions/vm/vmcrosspoolmigrateaction.h \
    xen/actions/vm/vmcopyaction.h \
    xen/actions/vm/vmmoveaction.h \
    xen/actions/pool/addhosttopoolaction.h \
    xen/actions/pool/createpoolaction.h \
    xen/actions/pool/ejecthostfrompoolaction.h \
    xen/actions/pool/destroypoolaction.h \
    xen/actions/pool/rotatepoolsecretaction.h \
    xen/actions/pool/enablehaaction.h \
    xen/actions/pool/disablehaaction.h \
    xen/actions/pool/sethaprioritiesaction.h \
    xen/actions/pool/emergencytransitiontomasteraction.h \
    xen/actions/pool/designatenewmasteraction.h \
    xen/actions/pool/syncdatabaseaction.h \
    xen/actions/pool/setpoolnameanddescriptionaction.h \
    xen/actions/pool/setsrasdefaultaction.h \
    xen/actions/pool/setpoolpropertyaction.h \
    xen/actions/pool/setssllegacyaction.h \
    xen/actions/network/changenetworkingaction.h \
    xen/actions/network/createbondaction.h \
    xen/actions/network/destroybondaction.h \
    xen/actions/network/createsriovaction.h \
    xen/actions/network/networkingactionhelpers.h \
    xen/actions/network/rescanpifsaction.h \
    xen/actions/vif/createvifaction.h \
    xen/actions/vif/deletevifaction.h \
    xen/actions/vif/plugvifaction.h \
    xen/actions/vif/unplugvifaction.h \
    xen/actions/vif/updatevifaction.h \
    xen/actions/delegatedasyncoperation.h \
    utils/encryption.h \
    network/comparableaddress.h \
    collections/observablelist.h \
    xen/network/connectionsmanager.h \
    operations/producerconsumerqueue.h \
    operations/multipleoperation.h \
    operations/paralleloperation.h \
    operations/operationlauncher.h \
    customfields/customfielddefinition.h \
    customfields/customfieldsmanager.h \
    xen/dockercontainer.h \
    xen/folder.h \
    xen/blob.h \
    xen/bond.h \
    xen/certificate.h \
    xen/cluster.h \
    xen/console.h \
    xen/event.h \
    xen/feature.h \
    xen/gpugroup.h \
    xen/hostcpu.h \
    xen/hostcrashdump.h \
    xen/hostpatch.h \
    xen/poolpatch.h \
    xen/poolupdate.h \
    xen/pusb.h \
    xen/sm.h \
    xen/role.h \
    xen/user.h \
    otherconfig/otherconfigandtagswatcher.h

# Installation
target.path = $$[QT_INSTALL_LIBS]
INSTALLS += target
